DROP DATABASE IF EXISTS "MarksDB";
CREATE ROLE REPLACE_USERNAME WITH LOGIN PASSWORD 'REPLACE_PASSWORD';
CREATE DATABASE "MarksDB";
\c MarksDB
CREATE TABLE IF NOT EXISTS MARKS(
ID SERIAL PRIMARY KEY,
IP_ADDRESS CIDR UNIQUE,
PRESENTATION_MARK NUMERIC(5, 2) NOT NULL,
PROPOSAL_MARK NUMERIC(5, 2) NOT NULL,
REPORT_MARK NUMERIC(5, 2) NOT NULL,
TOTAL_MARK NUMERIC(5, 2) NOT NULL
);
GRANT ALL PRIVILEGES ON MARKS TO REPLACE_USERNAME;
GRANT ALL PRIVILEGES ON marks_id_seq to REPLACE_USERNAME;
